name: Python Package using Conda

on: [push, pull_request]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install Dependencies
      run: |
        pip install pip -U
        pip install flake8
    - name: Run ls -la in workspace
      run: |
        ls -la
    - name: Run flake8
      run: |
        flake8 .
    - name: Run Hello World
      run: |
        python3 hello_world.py
